# Pandas DataFrame — Complete Practice Notebook

This notebook walks through every core Pandas DataFrame topic using **three real datasets**:

- `batsman_runs_ipl.csv` — total runs scored by IPL batsmen
- `ipl-matches.csv` — IPL match-by-match data (2008–2022)
- `movies.csv` — Bollywood movies dataset (IMDB info)

Make sure these three CSV files are in the **same folder** as this notebook before running it.

Work through each section top to bottom, and try tweaking the code yourself to test your understanding.

In [1]:
import numpy as np
import pandas as pd

pd.set_option('display.max_columns', 25)
pd.set_option('display.width', 150)

## 1. Creating a DataFrame

### 1.1 Using a list

In [2]:
# A simple list -> single column DataFrame
students = ['Yuvi', 'Aman', 'Riya', 'Simran']
df_list = pd.DataFrame(students, columns=['name'])
df_list

     name
0    Yuvi
1    Aman
2    Riya
3  Simran

In [3]:
# List of lists -> multiple columns
data = [
    ['Yuvi', 25, 'Pune'],
    ['Aman', 23, 'Mumbai'],
    ['Riya', 24, 'Delhi']
]
df_list2 = pd.DataFrame(data, columns=['name', 'age', 'city'])
df_list2

   name  age    city
0  Yuvi   25    Pune
1  Aman   23  Mumbai
2  Riya   24   Delhi

### 1.2 Using a dictionary

In [4]:
data_dict = {
    'name': ['Yuvi', 'Aman', 'Riya', 'Simran'],
    'age': [25, 23, 24, 22],
    'city': ['Pune', 'Mumbai', 'Delhi', 'Pune']
}
df_dict = pd.DataFrame(data_dict)
df_dict

     name  age    city
0    Yuvi   25    Pune
1    Aman   23  Mumbai
2    Riya   24   Delhi
3  Simran   22    Pune

### 1.3 Using `read_csv` — our 3 real datasets

In [5]:
batsman = pd.read_csv('batsman_runs_ipl.csv')
matches = pd.read_csv('ipl-matches.csv')
movies = pd.read_csv('movies.csv')

batsman.head()

           batter  batsman_run
0  A Ashish Reddy          280
1        A Badoni          161
2      A Chandila            4
3        A Chopra           53
4     A Choudhary           25

In [6]:
matches.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

In [7]:
movies.head()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)

## 2. Attributes and Methods

We'll mostly use `movies` and `matches` here since they have many rows/columns.

### 2.1 `shape`

In [8]:
print(batsman.shape)
print(matches.shape)
print(movies.shape)

(605, 2)
(950, 20)
(1629, 18)

### 2.2 `dtypes`

In [9]:
movies.dtypes

title_x                 str
imdb_id                 str
poster_path             str
wiki_link               str
title_y                 str
original_title          str
is_adult              int64
year_of_release       int64
runtime                 str
genres                  str
imdb_rating         float64
imdb_votes            int64
story                   str
summary                 str
tagline                 str
actors                  str
wins_nominations        str
release_date            str
dtype: object

### 2.3 `index`

In [10]:
movies.index

RangeIndex(start=0, stop=1629, step=1)

### 2.4 `describe()` — summary statistics of numeric columns

In [11]:
movies.describe()

       is_adult  year_of_release  imdb_rating     imdb_votes
count    1629.0      1629.000000  1629.000000    1629.000000
mean        0.0      2010.263966     5.557459    5384.263352
std         0.0         5.381542     1.567609   14552.103231
min         0.0      2001.000000     0.000000       0.000000
25%         0.0      2005.000000     4.400000     233.000000
50%         0.0      2011.000000     5.600000    1000.000000
75%         0.0      2015.000000     6.800000    4287.000000
max         0.0      2019.000000     9.400000  310481.000000

### 2.5 `info()`

In [12]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 1629 entries, 0 to 1628
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_x           1629 non-null   str
 1   imdb_id           1629 non-null   str
 2   poster_path       1526 non-null   str
 3   wiki_link         1629 non-null   str
 4   title_y           1629 non-null   str
 5   original_title    1629 non-null   str
 6   is_adult          1629 non-null   int64
 7   year_of_release   1629 non-null   int64
 8   runtime           1629 non-null   str
 9   genres            1629 non-null   str
 10  imdb_rating       1629 non-null   float64
 11  imdb_votes        1629 non-null   int64
 12  story             1609 non-null   str
 13  summary           1629 non-null   str
 14  tagline           557 non-null    str
 15  actors            1624 non-null   str
 16  wins_nominations  707 non-null    str
 17  release_date      1522 non-null   str
dtypes: float64(1), int64(3), str(14)
memory usage: 229.2 KB

### 2.6 `columns`

In [13]:
movies.columns

Index(['title_x', 'imdb_id', 'poster_path', 'wiki_link', 'title_y', 'original_title', 'is_adult', 'year_of_release', 'runtime', 'genres',
       'imdb_rating', 'imdb_votes', 'story', 'summary', 'tagline', 'actors', 'wins_nominations', 'release_date'],
      dtype='str')

### 2.7 `values` — underlying numpy array

In [14]:
batsman.values

array([['A Ashish Reddy', 280],
       ['A Badoni', 161],
       ['A Chandila', 4],
       ...,
       ['Younis Khan', 3],
       ['Yuvraj Singh', 2754],
       ['Z Khan', 117]], shape=(605, 2), dtype=object)

### 2.8 `head()`, `tail()`, `sample()`

In [15]:
display(matches.head(3))
display(matches.tail(3))
display(matches.sample(3))   # random rows, run it multiple times

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
534,729313,NaN,2014-04-28,2014,18,Kings XI Punjab,Royal Challengers Bangalore,Dubai International Cricket Stadium,Kings XI Punjab,field,N,Kings XI Punjab,Wickets,5.0,NaN,Sandeep Sharma,"['CA Pujara', 'V Sehwag', 'WP Saha', 'GJ Maxwe...","['CH Gayle', 'PA Patel', 'V Kohli', 'YV Takawa...",BF Bowden,S Ravi
190,1216496,NaN,2020-09-22,2020/21,4,Rajasthan Royals,Chennai Super Kings,Sharjah Cricket Stadium,Chennai Super Kings,field,N,Rajasthan Royals,Runs,16.0,NaN,SV Samson,"['YBK Jaiswal', 'SPD Smith', 'SV Samson', 'DA ...","['M Vijay', 'SR Watson', 'F du Plessis', 'SM C...",C Shamshuddin,VA Kulkarni
470,829749,Ahmedabad,2015-04-24,2015,22,Rajasthan Royals,Royal Challengers Bangalore,"Sardar Patel Stadium, Motera",Royal Challengers Bangalore,field,N,Royal Challengers Bangalore,Wickets,9.0,NaN,MA Starc,"['AM Rahane', 'SR Watson', 'SPD Smith', 'KK Na...","['CH Gayle', 'V Kohli', 'AB de Villiers', 'Man...",M Erasmus,S Ravi

### 2.9 `isnull()`

In [16]:
movies.isnull().sum()   # count of missing values per column

title_x                0
imdb_id                0
poster_path          103
wiki_link              0
title_y                0
original_title         0
is_adult               0
year_of_release        0
runtime                0
genres                 0
imdb_rating            0
imdb_votes             0
story                 20
summary                0
tagline             1072
actors                 5
wins_nominations     922
release_date         107
dtype: int64

### 2.10 `duplicated()`

In [17]:
print(matches.duplicated().sum())   # no full-row duplicates expected
matches[matches.duplicated()]

0

Empty DataFrame
Columns: [ID, City, Date, Season, MatchNumber, Team1, Team2, Venue, TossWinner, TossDecision, SuperOver, WinningTeam, WonBy, Margin, method, Player_of_Match, Team1Players, Team2Players, Umpire1, Umpire2]
Index: []

### 2.11 `rename()`

In [18]:
movies.rename(columns={'title_x': 'title', 'imdb_rating': 'rating'}).head(2)
# note: rename() returns a NEW dataframe by default (inplace=False)

,title,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)

## 3. Mathematical Methods

In [19]:
print('Sum of all runs      :', batsman['batsman_run'].sum())
print('Variance of runs     :', batsman['batsman_run'].var())
print('Max runs by a batsman:', batsman['batsman_run'].max())
print('Mean runs            :', batsman['batsman_run'].mean())
print('Median runs          :', batsman['batsman_run'].median())
print('Std deviation        :', batsman['batsman_run'].std())

Sum of all runs      : 280979
Variance of runs     : 970762.5995402549
Max runs by a batsman: 6634
Mean runs            : 464.42809917355373
Median runs          : 73.0
Std deviation        : 985.2728553757355

In [20]:
# Applying to the whole numeric part of a bigger dataframe
movies[['imdb_rating', 'imdb_votes']].mean()

imdb_rating       5.557459
imdb_votes     5384.263352
dtype: float64

## 4. Selecting Columns from a DataFrame

### 4.1 Single column

In [21]:
movies['title_x'].head()      # returns a Series
# movies.title_x.head()       # dot notation also works (avoid if column name has spaces)

0                Uri: The Surgical Strike
1                           Battalion 609
2    The Accidental Prime Minister (film)
3                         Why Cheat India
4                         Evening Shadows
Name: title_x, dtype: str

### 4.2 Multiple columns

In [22]:
movies[['title_x', 'year_of_release', 'imdb_rating']].head()

                                title_x  year_of_release  imdb_rating
0              Uri: The Surgical Strike             2019          8.4
1                         Battalion 609             2019          4.1
2  The Accidental Prime Minister (film)             2019          6.1
3                       Why Cheat India             2019          6.0
4                       Evening Shadows             2018          7.3

## 5. Selecting Rows from a DataFrame

### 5.1 `set_index`

In [23]:
movies_indexed = movies.set_index('title_x')
movies_indexed.head(3)

,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
title_x,,,,,,,,,,,,,,,,,
Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)

### 5.2 `loc` — label based

In [24]:
# single row by label
movies_indexed.loc['Uri: The Surgical Strike']

imdb_id                                                     tt8291224
poster_path         https://upload.wikimedia.org/wikipedia/en/thum...
wiki_link           https://en.wikipedia.org/wiki/Uri:_The_Surgica...
title_y                                      Uri: The Surgical Strike
original_title                               Uri: The Surgical Strike
is_adult                                                            0
year_of_release                                                  2019
runtime                                                           138
genres                                               Action|Drama|War
imdb_rating                                                       8.4
imdb_votes                                                      35112
story               Divided over five chapters  the film chronicle...
summary             Indian army special forces execute a covert op...
tagline                                                           NaN
actors              Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...
wins_nominations                                               4 wins
release_date                                    11 January 2019 (USA)
Name: Uri: The Surgical Strike, dtype: object

In [25]:
# multiple rows by label (fancy indexing)
movies_indexed.loc[['Uri: The Surgical Strike', 'Battalion 609']]

,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
title_x,,,,,,,,,,,,,,,,,
Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)

### 5.3 `iloc` — position based

In [26]:
matches.iloc[0]          # first row

ID                                                           1312200
City                                                       Ahmedabad
Date                                                      2022-05-29
Season                                                          2022
MatchNumber                                                    Final
Team1                                               Rajasthan Royals
Team2                                                 Gujarat Titans
Venue                               Narendra Modi Stadium, Ahmedabad
TossWinner                                          Rajasthan Royals
TossDecision                                                     bat
SuperOver                                                          N
WinningTeam                                           Gujarat Titans
WonBy                                                        Wickets
Margin                                                           7.0
method                                                           NaN
Player_of_Match                                            HH Pandya
Team1Players       ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...
Team2Players       ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...
Umpire1                                                  CB Gaffaney
Umpire2                                                  Nitin Menon
Name: 0, dtype: object

In [27]:
matches.iloc[0:5]        # first 5 rows (simple row selection, slice)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

In [28]:
matches.iloc[[0, 5, 10]] # fancy indexing - specific positions

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
5,1304115,Mumbai,2022-05-21,2022,69,Delhi Capitals,Mumbai Indians,"Wankhede Stadium, Mumbai",Mumbai Indians,field,N,Mumbai Indians,Wickets,5.0,NaN,JJ Bumrah,"['PP Shaw', 'DA Warner', 'MR Marsh', 'RR Pant'...","['Ishan Kishan', 'RG Sharma', 'D Brevis', 'Til...",Nitin Menon,Tapan Sharma
10,1304110,Navi Mumbai,2022-05-16,2022,64,Delhi Capitals,Punjab Kings,"Dr DY Patil Sports Academy, Mumbai",Punjab Kings,field,N,Delhi Capitals,Runs,17.0,NaN,SN Thakur,"['DA Warner', 'SN Khan', 'MR Marsh', 'Lalit Ya...","['JM Bairstow', 'S Dhawan', 'PBB Rajapaksa', '...",GR Sadashiv Iyer,Nitin Menon

### 5.4 Simple & multiple row selection recap

In [29]:
# using loc with default integer index
matches.loc[0]           # single row
matches.loc[0:3]         # multiple rows, label-slice is INCLUSIVE of endpoint
matches.loc[[0, 2, 4]]   # fancy indexing with loc

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

## 6. Selecting Both Rows and Columns

In [30]:
# loc: rows by label, columns by name
matches.loc[0:4, ['Team1', 'Team2', 'WinningTeam']]

                         Team1                 Team2                  WinningTeam
0             Rajasthan Royals        Gujarat Titans               Gujarat Titans
1  Royal Challengers Bangalore      Rajasthan Royals             Rajasthan Royals
2  Royal Challengers Bangalore  Lucknow Super Giants  Royal Challengers Bangalore
3             Rajasthan Royals        Gujarat Titans               Gujarat Titans
4          Sunrisers Hyderabad          Punjab Kings                 Punjab Kings

In [31]:
# iloc: rows and columns by position
matches.iloc[0:5, 0:4]

        ID       City        Date Season
0  1312200  Ahmedabad  2022-05-29   2022
1  1312199  Ahmedabad  2022-05-27   2022
2  1312198    Kolkata  2022-05-25   2022
3  1312197    Kolkata  2022-05-24   2022
4  1304116     Mumbai  2022-05-22   2022

In [32]:
movies_indexed.loc['Uri: The Surgical Strike', ['year_of_release', 'imdb_rating']]

year_of_release    2019.0
imdb_rating           8.4
Name: Uri: The Surgical Strike, dtype: float64

## 7. Filtering DataFrames

In [33]:
# movies with imdb rating above 8
high_rated = movies[movies['imdb_rating'] > 8]
high_rated[['title_x', 'imdb_rating']].head()

                     title_x  imdb_rating
0   Uri: The Surgical Strike          8.4
11                 Gully Boy          8.2
37         Article 15 (film)          8.3
40           Super 30 (film)          8.2
41      Family of Thakurganj          9.4

In [34]:
# multiple conditions: high rated AND released after 2015
filtered = movies[(movies['imdb_rating'] > 8) & (movies['year_of_release'] > 2015)]
filtered[['title_x', 'year_of_release', 'imdb_rating']]

                            title_x  year_of_release  imdb_rating
0          Uri: The Surgical Strike             2019          8.4
11                        Gully Boy             2019          8.2
37                Article 15 (film)             2019          8.3
40                  Super 30 (film)             2019          8.2
41             Family of Thakurganj             2019          9.4
53                      Section 375             2019          8.4
58                Ghost (2019 film)             2019          8.7
59                 Bala (2019 film)             2019          8.2
62                   Saand Ki Aankh             2019          8.9
64                      Ujda Chaman             2019          8.1
84                        Mukkabaaz             2017          8.1
143                         Tumbbad             2018          8.2
146                       Andhadhun             2018          8.4
192        Sachin: A Billion Dreams             2017          8.6
207                      G Kutta Se             2017          8.3
216  Yadvi – The Dignified Princess             2017          8.2
219                Raag Desh (film)             2017          8.3
325                Pink (2016 film)             2016          8.2
354                   Dangal (film)             2016          8.4

In [35]:
# matches won by a specific team
csk_wins = matches[matches['WinningTeam'] == 'Chennai Super Kings']
csk_wins[['Season', 'Team1', 'Team2', 'WinningTeam']].head()

   Season                Team1                        Team2          WinningTeam
19   2022  Chennai Super Kings               Delhi Capitals  Chennai Super Kings
28   2022  Chennai Super Kings          Sunrisers Hyderabad  Chennai Super Kings
41   2022       Mumbai Indians          Chennai Super Kings  Chennai Super Kings
52   2022  Chennai Super Kings  Royal Challengers Bangalore  Chennai Super Kings
74   2021  Chennai Super Kings        Kolkata Knight Riders  Chennai Super Kings

In [36]:
# filtering using isin()
final_teams = matches[matches['Team1'].isin(['Mumbai Indians', 'Chennai Super Kings'])]
final_teams[['Season', 'Team1', 'Team2']].head()

   Season                Team1             Team2
6    2022  Chennai Super Kings  Rajasthan Royals
12   2022  Chennai Super Kings    Gujarat Titans
15   2022  Chennai Super Kings    Mumbai Indians
19   2022  Chennai Super Kings    Delhi Capitals
23   2022       Mumbai Indians    Gujarat Titans

## 8. Adding New Columns

### 8.1 Brand new column

In [37]:
movies_copy = movies.copy()
movies_copy['is_recent'] = movies_copy['year_of_release'] > 2015
movies_copy[['title_x', 'year_of_release', 'is_recent']].head()

                                title_x  year_of_release  is_recent
0              Uri: The Surgical Strike             2019       True
1                         Battalion 609             2019       True
2  The Accidental Prime Minister (film)             2019       True
3                       Why Cheat India             2019       True
4                       Evening Shadows             2018       True

### 8.2 Column derived from existing column(s)

In [38]:
batsman_copy = batsman.copy()
batsman_copy['runs_per_100'] = batsman_copy['batsman_run'] / 100
batsman_copy.head()

           batter  batsman_run  runs_per_100
0  A Ashish Reddy          280          2.80
1        A Badoni          161          1.61
2      A Chandila            4          0.04
3        A Chopra           53          0.53
4     A Choudhary           25          0.25

In [39]:
movies_copy['votes_per_rating_point'] = movies_copy['imdb_votes'] / movies_copy['imdb_rating']
movies_copy[['title_x', 'imdb_votes', 'imdb_rating', 'votes_per_rating_point']].head()

                                title_x  imdb_votes  imdb_rating  votes_per_rating_point
0              Uri: The Surgical Strike       35112          8.4             4180.000000
1                         Battalion 609          73          4.1               17.804878
2  The Accidental Prime Minister (film)        5549          6.1              909.672131
3                       Why Cheat India        1891          6.0              315.166667
4                       Evening Shadows         280          7.3               38.356164

## 9. Important DataFrame Functions

### 9.1 `astype`

In [40]:
movies_copy['year_of_release'] = movies_copy['year_of_release'].astype('int32')
movies_copy['year_of_release'].dtype

dtype('int32')

### 9.2 `value_counts`

In [41]:
matches['WinningTeam'].value_counts()

WinningTeam
Mumbai Indians                 131
Chennai Super Kings            121
Kolkata Knight Riders          114
Royal Challengers Bangalore    109
Rajasthan Royals                96
Kings XI Punjab                 88
Sunrisers Hyderabad             75
Delhi Daredevils                67
Delhi Capitals                  36
Deccan Chargers                 29
Punjab Kings                    13
Gujarat Lions                   13
Gujarat Titans                  12
Pune Warriors                   12
Rising Pune Supergiant          10
Lucknow Super Giants             9
Kochi Tuskers Kerala             6
Rising Pune Supergiants          5
Name: count, dtype: int64

In [42]:
matches['Season'].value_counts()

Season
2013       76
2022       74
2012       74
2011       73
2021       60
2020/21    60
2019       60
2018       60
2016       60
2014       60
2009/10    60
2017       59
2015       59
2007/08    58
2009       57
Name: count, dtype: int64

### 9.3 `sort_values`

In [43]:
batsman.sort_values('batsman_run', ascending=False).head(10)

             batter  batsman_run
569         V Kohli         6634
462        S Dhawan         6244
130       DA Warner         5883
430       RG Sharma         5881
493        SK Raina         5536
27   AB de Villiers         5181
108        CH Gayle         4997
339        MS Dhoni         4978
452      RV Uthappa         4954
256      KD Karthik         4377

In [44]:
movies.sort_values(['year_of_release', 'imdb_rating'], ascending=[True, False]).head()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
1567,Lagaan,tt0169102,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Lagaan,Lagaan: Once Upon a Time in India,Lagaan: Once Upon a Time in India,0,2001,224,Adventure|Drama|Musical,8.1,95686,This is the story about the resilience shown b...,The people of a small village in Victorian Ind...,Once upon a time in India,Aamir Khan|Gracy Singh|Rachel Shelley|Paul Bla...,Nominated for 1 Oscar,15 June 2001 (USA)
1568,Lagaan,tt0169102,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Lagaan:_Once_Upo...,Lagaan: Once Upon a Time in India,Lagaan: Once Upon a Time in India,0,2001,224,Adventure|Drama|Musical,8.1,95686,This is the story about the resilience shown b...,The people of a small village in Victorian Ind...,Once upon a time in India,Aamir Khan|Gracy Singh|Rachel Shelley|Paul Bla...,Nominated for 1 Oscar,15 June 2001 (USA)
1571,Dil Chahta Hai,tt0292490,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Dil_Chahta_Hai,Dil Chahta Hai,Dil Chahta Hai,0,2001,183,Comedy|Drama|Romance,8.1,62313,Three young men Akash Sameer and Siddharth a...,Three inseparable childhood friends are just o...,Welcome to a summer of their lives you will ne...,Aamir Khan|Saif Ali Khan|Akshaye Khanna|Preity...,22 wins & 37 nominations,10 August 2001 (India)
1607,Nayak (2001 Hindi film),tt0291376,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Nayak_(2001_Hind...,Nayak: The Real Hero,Nayak: The Real Hero,0,2001,187,Action|Drama|Thriller,7.8,12522,Employed as a camera-man at a popular televisi...,A man accepts a challenge by the chief ministe...,Fight the power,Anil Kapoor|Rani Mukerji|Amrish Puri|Johnny Le...,2 nominations,7 September 2001 (India)
1589,Chandni Bar,tt0267363,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Chandni_Bar,Chandni Bar,Chandni Bar,0,2001,150,Crime|Drama,7.6,2284,Mumtaz is a village girl whose family is kille...,A displaced woman is forced to become a beer-b...,NaN,Tabu|Atul Kulkarni|Rajpal Yadav|Shri Vallabh V...,7 wins & 14 nominations,28 September 2001 (India)

### 9.4 `rank`

In [45]:
batsman_copy = batsman.copy()
batsman_copy['run_rank'] = batsman_copy['batsman_run'].rank(ascending=False)
batsman_copy.sort_values('run_rank').head(10)

             batter  batsman_run  run_rank
569         V Kohli         6634       1.0
462        S Dhawan         6244       2.0
130       DA Warner         5883       3.0
430       RG Sharma         5881       4.0
493        SK Raina         5536       5.0
27   AB de Villiers         5181       6.0
108        CH Gayle         4997       7.0
339        MS Dhoni         4978       8.0
452      RV Uthappa         4954       9.0
256      KD Karthik         4377      10.0

### 9.5 `set_index` / `reset_index`

In [46]:
batsman_indexed = batsman.set_index('batter')
display(batsman_indexed.head())

batsman_back = batsman_indexed.reset_index()
batsman_back.head()

                batsman_run
batter
A Ashish Reddy          280
A Badoni                161
A Chandila                4
A Chopra                 53
A Choudhary              25

           batter  batsman_run
0  A Ashish Reddy          280
1        A Badoni          161
2      A Chandila            4
3        A Chopra           53
4     A Choudhary           25

### 9.6 Rename column vs rename index

In [47]:
# rename a column
batsman.rename(columns={'batsman_run': 'total_runs'}).head(2)

           batter  total_runs
0  A Ashish Reddy         280
1        A Badoni         161

In [48]:
# rename index labels
batsman_indexed.rename(index={'A Ashish Reddy': 'AA Reddy'}).head(2)

          batsman_run
batter
AA Reddy          280
A Badoni          161

### 9.7 `unique` and `nunique`

In [49]:
print(matches['Season'].unique())
print('Number of unique seasons:', matches['Season'].nunique())

<StringArray>
['2022', '2021', '2020/21', '2019', '2018', '2017', '2016', '2015', '2014', '2013', '2012', '2011', '2009/10', '2009', '2007/08']
Length: 15, dtype: str
Number of unique seasons: 15

In [50]:
print('Number of unique teams that won a match:', matches['WinningTeam'].nunique())

Number of unique teams that won a match: 18

### 9.8 `isnull`, `notnull`, `hasnans`

In [51]:
print(movies['imdb_rating'].isnull().sum())
print(movies['imdb_rating'].notnull().sum())
print(movies['imdb_rating'].hasnans)

0
1629
False

### 9.9 `dropna`

In [52]:
movies_dropped = movies.dropna(subset=['imdb_rating'])
print('Before:', movies.shape)
print('After :', movies_dropped.shape)

Before: (1629, 18)
After : (1629, 18)

### 9.10 `fillna`

In [53]:
movies_filled = movies.copy()
movies_filled['imdb_rating'] = movies_filled['imdb_rating'].fillna(movies_filled['imdb_rating'].mean())
movies_filled['imdb_rating'].isnull().sum()

np.int64(0)

### 9.11 `drop_duplicates()` — `keep` parameter

In [54]:
# duplicate rows based on 'Season' + 'Team1' + 'Team2' combo, just to demonstrate 'keep'
subset_cols = ['Season', 'Team1', 'Team2']

print('keep="first" (default) shape:', matches.drop_duplicates(subset=subset_cols, keep='first').shape)
print('keep="last" shape          :', matches.drop_duplicates(subset=subset_cols, keep='last').shape)
print('keep=False shape           :', matches.drop_duplicates(subset=subset_cols, keep=False).shape)

keep="first" (default) shape: (803, 20)
keep="last" shape          : (803, 20)
keep=False shape           : (666, 20)

### 9.12 `drop`

In [55]:
# drop a column
movies.drop(columns=['poster_path', 'wiki_link']).head(2)

,title_x,imdb_id,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)

In [56]:
# drop rows by index label
matches.drop(index=[0, 1]).head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
5,1304115,Mumbai,2022-05-21,2022,69,Delhi Capitals,Mumbai Indians,"Wankhede Stadium, Mumbai",Mumbai Indians,field,N,Mumbai Indians,Wickets,5.0,NaN,JJ Bumrah,"['PP Shaw', 'DA Warner', 'MR Marsh', 'RR Pant'...","['Ishan Kishan', 'RG Sharma', 'D Brevis', 'Til...",Nitin Menon,Tapan Sharma
6,1304114,Mumbai,2022-05-20,2022,68,Chennai Super Kings,Rajasthan Royals,"Brabourne Stadium, Mumbai",Chennai Super Kings,bat,N,Rajasthan Royals,Wickets,5.0,NaN,R Ashwin,"['RD Gaikwad', 'DP Conway', 'MM Ali', 'N Jagad...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,NA Patwardhan

### 9.13 `apply`

In [57]:
# apply on a single column - custom function
def rating_category(rating):
    if pd.isna(rating):
        return 'Unknown'
    elif rating >= 8:
        return 'Excellent'
    elif rating >= 6:
        return 'Good'
    else:
        return 'Average'

movies_copy['rating_category'] = movies_copy['imdb_rating'].apply(rating_category)
movies_copy[['title_x', 'imdb_rating', 'rating_category']].head()

                                title_x  imdb_rating rating_category
0              Uri: The Surgical Strike          8.4       Excellent
1                         Battalion 609          4.1         Average
2  The Accidental Prime Minister (film)          6.1            Good
3                       Why Cheat India          6.0            Good
4                       Evening Shadows          7.3            Good

In [58]:
# apply with lambda across a row (axis=1)
matches['match_summary'] = matches.apply(lambda row: f"{row['Team1']} vs {row['Team2']} ({row['Season']})", axis=1)
matches[['match_summary']].head()

                                       match_summary
0          Rajasthan Royals vs Gujarat Titans (2022)
1  Royal Challengers Bangalore vs Rajasthan Royal...
2  Royal Challengers Bangalore vs Lucknow Super G...
3          Rajasthan Royals vs Gujarat Titans (2022)
4         Sunrisers Hyderabad vs Punjab Kings (2022)

## 🎯 Practice Exercises

Try these on your own to reinforce everything above:

1. Find the top 5 batsmen by total runs using `sort_values` + `head`.
2. Find how many movies were released each year using `value_counts`.
3. Create a new column in `movies` that categorizes movies as `'Blockbuster'` if `imdb_votes > 50000`, else `'Regular'`, using `apply`.
4. Use `loc` to find all matches played in `'Mumbai'` city with `TossDecision == 'bat'`.
5. Use `drop_duplicates` on the `matches` dataframe to find the list of unique venues.
6. Use `fillna` to fill missing `runtime` values in `movies` with the median runtime.
7. Rank batsmen by `batsman_run` and find the rank of a specific player using `loc`.